netG:
  _target_: ttslearn.contrib.multispk_tacotron2.MultiSpkTacotron2
  num_vocab: 52
  reduction_factor: 2
  embed_dim: 512
  encoder_hidden_dim: 512
  decoder_out_dim: 80
  encoder_conv_layers: 3
  encoder_conv_channels: 512
  encoder_conv_kernel_size: 5
  encoder_dropout: 0.5
  attention_hidden_dim: 128
  attention_conv_channels: 32
  attention_conv_kernel_size: 31
  decoder_layers: 2
  decoder_hidden_dim: 1024
  decoder_prenet_layers: 2
  decoder_prenet_hidden_dim: 256
  decoder_prenet_dropout: 0.5
  postnet_layers: 5
  postnet_channels: 512
  postnet_kernel_size: 5
  postnet_dropout: 0.5
  decoder_zoneout: 0.1
  n_spks: 101
  spk_emb_dim: 64 # for speaker embedding # NOTE: デフォルト
  # spk_emb_dim: ${model.xvector.spk_emb_dim} # NOTE: x-vectorを用いる場合
  # spk_emb_dim: 512 # NOTE: x-vectorを用いる場合

spk_rec_model:
  project_dir: "exp/simpleSR/2023-07-10_23:04:46"
  model_path: "/home/hosoi/git/ssr/${model.spk_rec_model.project_dir}/output/checkpoints/last.ckpt"
  netG:
    _target_: ttslearn.contrib.x_vector.X_vector
    input_dim: ${model.netG.decoder_out_dim}
    num_classes: 2
    # num_classes: 100

xvector:
  spk_emb_dim: 64 # 512
  # spk_emb_matrix_path: /home/hosoi/git/ssr/outputs/x_vec_mean/stacked_xvector_matrix.npy
  # spk_emb_matrix_path: /home/hosoi/git/ssr/outputs/x_vec_mean_d64_norm/stacked_xvector_matrix.npy
  # spk_emb_matrix_path: /home/hosoi/git/ssr/outputs/x_vec_baseline/stacked_xvector_matrix.npy
  spk_emb_matrix_path: /home/hosoi/git/ssr/outputs/x_vec_baseline_wo_norm/stacked_xvector_matrix.npy
